# Generated by Django 4.2.7 on 2023-11-24 16:53

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PdfStorage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uuid", models.UUIDField()),
                ("isin", models.CharField(max_length=12)),
                ("cusip", models.CharField(max_length=9)),
                ("common_name", models.CharField(max_length=255)),
                ("ticker", models.CharField(max_length=4)),
                ("raw_data", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
