# Generated by Django 4.2.7 on 2023-11-25 16:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("upper_lake", "0002_alter_pdfstorage_table"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="pdfstorage",
            table="pdf_storage",
        ),
    ]
