# Generated by Django 4.2.7 on 2023-11-25 17:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("upper_lake", "0003_alter_pdfstorage_table"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="pdfstorage",
            table="section_storage_10_k_raw",
        ),
    ]
