# Generated by Django 4.2.7 on 2023-12-03 23:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("upper_lake", "0005_alter_pdfstorage_table"),
    ]

    operations = [
        migrations.CreateModel(
            name="RawTextData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("filing_url", models.TextField()),
                ("section", models.TextField()),
                ("text", models.TextField()),
            ],
            options={
                "db_table": "raw_text_data",
            },
        ),
        migrations.CreateModel(
            name="SecurityDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField()),
                ("ticker", models.CharField(max_length=9)),
                ("cik", models.CharField(max_length=20)),
                ("cusip", models.CharField(max_length=9)),
                ("exchange", models.TextField()),
                ("isDelisted", models.BooleanField()),
                ("category", models.TextField()),
                ("sector", models.TextField()),
                ("industry", models.TextField()),
                ("sic", models.TextField()),
                ("sicSector", models.TextField()),
                ("sicIndustry", models.TextField()),
                ("currency", models.TextField()),
                ("location", models.TextField()),
                ("sec_id", models.TextField()),
            ],
            options={
                "db_table": "security_details",
            },
        ),
    ]
