# Generated by Django 4.2.7 on 2023-12-11 16:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("upper_lake", "0006_rawtextdata_securitydetails"),
    ]

    operations = [
        migrations.AlterField(
            model_name="securitydetails",
            name="sec_id",
            field=models.TextField(max_length=455),
        ),
    ]
