# Generated by Django 4.2.7 on 2023-12-11 16:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("upper_lake", "0007_alter_securitydetails_sec_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="securitydetails",
            name="cik",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="securitydetails",
            name="cusip",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="securitydetails",
            name="sec_id",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="securitydetails",
            name="ticker",
            field=models.TextField(),
        ),
    ]
