# Generated by Django 4.2.7 on 2023-12-17 23:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("upper_lake", "0008_alter_securitydetails_cik_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TenKData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ticker", models.CharField()),
                ("filing_date", models.DateField()),
                ("filing_url", models.TextField()),
                ("section_one", models.TextField()),
                ("section_one_a", models.TextField()),
                ("section_one_b", models.TextField()),
                ("section_two", models.TextField()),
                ("section_three", models.TextField()),
                ("section_four", models.TextField()),
                ("section_five", models.TextField()),
                ("section_six", models.TextField()),
                ("section_seven", models.TextField()),
                ("section_seven_a", models.TextField()),
                ("section_eight", models.TextField()),
                ("section_nine", models.TextField()),
                ("section_nine_a", models.TextField()),
                ("section_nine_b", models.TextField()),
                ("section_ten", models.TextField()),
                ("section_eleven", models.TextField()),
                ("section_twelve", models.TextField()),
                ("section_thirteen", models.TextField()),
                ("section_fourteen", models.TextField()),
                ("section_fifteen", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "raw_ten_k_data",
            },
        ),
    ]
