# Generated by Django 4.2.7 on 2024-01-05 16:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("upper_lake", "0009_tenkdata"),
    ]

    operations = [
        migrations.CreateModel(
            name="FilingUrls",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ticker", models.TextField()),
                ("filing_url", models.TextField()),
                ("text_version_filing", models.TextField()),
                ("index_page_filing", models.TextField()),
                ("date", models.TextField()),
                ("form", models.TextField()),
                ("cik", models.TextField()),
                ("company_name", models.TextField()),
            ],
            options={
                "db_table": "historic_filing_urls",
            },
        ),
    ]
