# Generated by Django 4.2.7 on 2024-01-06 00:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("upper_lake", "0010_filingurls"),
    ]

    operations = [
        migrations.DeleteModel(
            name="PdfStorage",
        ),
        migrations.DeleteModel(
            name="RawTextData",
        ),
    ]
