# Generated by Django 4.2.7 on 2024-01-16 00:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("upper_lake", "0011_delete_pdfstorage_delete_rawtextdata"),
    ]

    operations = [
        migrations.CreateModel(
            name="EightKData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ticker", models.CharField()),
                ("filing_date", models.DateField()),
                ("filing_url", models.TextField()),
                ("one_one", models.TextField()),
                ("one_two", models.TextField()),
                ("one_three", models.TextField()),
                ("one_four", models.TextField()),
                ("one_five", models.TextField()),
                ("two_one", models.TextField()),
                ("two_two", models.TextField()),
                ("two_three", models.TextField()),
                ("two_four", models.TextField()),
                ("two_five", models.TextField()),
                ("two_six", models.TextField()),
                ("three_one", models.TextField()),
                ("three_two", models.TextField()),
                ("three_three", models.TextField()),
                ("four_one", models.TextField()),
                ("four_two", models.TextField()),
                ("five_one", models.TextField()),
                ("five_two", models.TextField()),
                ("five_three", models.TextField()),
                ("five_four", models.TextField()),
                ("five_five", models.TextField()),
                ("five_six", models.TextField()),
                ("five_seven", models.TextField()),
                ("five_eight", models.TextField()),
                ("six_one", models.TextField()),
                ("six_two", models.TextField()),
                ("six_three", models.TextField()),
                ("six_four", models.TextField()),
                ("six_five", models.TextField()),
                ("six_six", models.TextField()),
                ("six_ten", models.TextField()),
                ("seven_one", models.TextField()),
                ("eight_one", models.TextField()),
                ("nine_one", models.TextField()),
                ("signature", models.TextField()),
            ],
            options={
                "db_table": "raw_eight_k_data",
            },
        ),
        migrations.CreateModel(
            name="TenQData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ticker", models.CharField()),
                ("filing_date", models.DateField()),
                ("filing_url", models.TextField()),
                ("part_1_item_1", models.TextField()),
                ("part_1_item_2", models.TextField()),
                ("part_1_item_3", models.TextField()),
                ("part_1_item_4", models.TextField()),
                ("part_2_item_1", models.TextField()),
                ("part_2_item_1a", models.TextField()),
                ("part_2_item_2", models.TextField()),
                ("part_2_item_3", models.TextField()),
                ("part_2_item_4", models.TextField()),
                ("part_2_item_5", models.TextField()),
                ("part_2_item_6", models.TextField()),
            ],
            options={
                "db_table": "raw_ten_q_data",
            },
        ),
    ]
