# Generated by Django 4.2.7 on 2024-06-08 04:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("upper_lake", "0013_processedeightkdata_processedtenkdata_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProcessedTenKSectionOne",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ticker", models.CharField()),
                ("filing_date", models.DateField()),
                ("filing_url", models.TextField()),
                ("section_one", models.TextField()),
            ],
            options={
                "db_table": "processed_ten_k_section_one",
            },
        ),
    ]
