# Generated by Django 4.2.7 on 2024-06-08 05:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("upper_lake", "0014_processedtenksectionone"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProcessedTenKSectionEight",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ticker", models.CharField()),
                ("filing_date", models.DateField()),
                ("filing_url", models.TextField()),
                ("section_eight", models.TextField()),
            ],
            options={
                "db_table": "processed_ten_k_section_eight",
            },
        ),
        migrations.CreateModel(
            name="ProcessedTenKSectionEleven",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ticker", models.CharField()),
                ("filing_date", models.DateField()),
                ("filing_url", models.TextField()),
                ("section_eleven", models.TextField()),
            ],
            options={
                "db_table": "processed_ten_k_section_eleven",
            },
        ),
        migrations.CreateModel(
            name="ProcessedTenKSectionFifteen",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ticker", models.CharField()),
                ("filing_date", models.DateField()),
                ("filing_url", models.TextField()),
                ("section_fifteen", models.TextField()),
            ],
            options={
                "db_table": "processed_ten_k_section_fifteen",
            },
        ),
        migrations.CreateModel(
            name="ProcessedTenKSectionFive",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ticker", models.CharField()),
                ("filing_date", models.DateField()),
                ("filing_url", models.TextField()),
                ("section_five", models.TextField()),
            ],
            options={
                "db_table": "processed_ten_k_section_five",
            },
        ),
        migrations.CreateModel(
            name="ProcessedTenKSectionFour",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ticker", models.CharField()),
                ("filing_date", models.DateField()),
                ("filing_url", models.TextField()),
                ("section_four", models.TextField()),
            ],
            options={
                "db_table": "processed_ten_k_section_four",
            },
        ),
        migrations.CreateModel(
            name="ProcessedTenKSectionFourteen",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ticker", models.CharField()),
                ("filing_date", models.DateField()),
                ("filing_url", models.TextField()),
                ("section_fourteen", models.TextField()),
            ],
            options={
                "db_table": "processed_ten_k_section_fourteen",
            },
        ),
        migrations.CreateModel(
            name="ProcessedTenKSectionNine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ticker", models.CharField()),
                ("filing_date", models.DateField()),
                ("filing_url", models.TextField()),
                ("section_nine", models.TextField()),
            ],
            options={
                "db_table": "processed_ten_k_section_nine",
            },
        ),
        migrations.CreateModel(
            name="ProcessedTenKSectionNineA",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ticker", models.CharField()),
                ("filing_date", models.DateField()),
                ("filing_url", models.TextField()),
                ("section_nine_a", models.TextField()),
            ],
            options={
                "db_table": "processed_ten_k_section_nine_a",
            },
        ),
        migrations.CreateModel(
            name="ProcessedTenKSectionNineB",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ticker", models.CharField()),
                ("filing_date", models.DateField()),
                ("filing_url", models.TextField()),
                ("section_nine_b", models.TextField()),
            ],
            options={
                "db_table": "processed_ten_k_section_nine_b",
            },
        ),
        migrations.CreateModel(
            name="ProcessedTenKSectionOneA",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ticker", models.CharField()),
                ("filing_date", models.DateField()),
                ("filing_url", models.TextField()),
                ("section_one_a", models.TextField()),
            ],
            options={
                "db_table": "processed_ten_k_section_one_a",
            },
        ),
        migrations.CreateModel(
            name="ProcessedTenKSectionOneB",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ticker", models.CharField()),
                ("filing_date", models.DateField()),
                ("filing_url", models.TextField()),
                ("section_one_b", models.TextField()),
            ],
            options={
                "db_table": "processed_ten_k_section_one_b",
            },
        ),
        migrations.CreateModel(
            name="ProcessedTenKSectionSeven",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ticker", models.CharField()),
                ("filing_date", models.DateField()),
                ("filing_url", models.TextField()),
                ("section_seven", models.TextField()),
            ],
            options={
                "db_table": "processed_ten_k_section_seven",
            },
        ),
        migrations.CreateModel(
            name="ProcessedTenKSectionSevenA",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ticker", models.CharField()),
                ("filing_date", models.DateField()),
                ("filing_url", models.TextField()),
                ("section_seven_a", models.TextField()),
            ],
            options={
                "db_table": "processed_ten_k_section_seven_a",
            },
        ),
        migrations.CreateModel(
            name="ProcessedTenKSectionSix",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ticker", models.CharField()),
                ("filing_date", models.DateField()),
                ("filing_url", models.TextField()),
                ("section_six", models.TextField()),
            ],
            options={
                "db_table": "processed_ten_k_section_six",
            },
        ),
        migrations.CreateModel(
            name="ProcessedTenKSectionTen",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ticker", models.CharField()),
                ("filing_date", models.DateField()),
                ("filing_url", models.TextField()),
                ("section_ten", models.TextField()),
            ],
            options={
                "db_table": "processed_ten_k_section_ten",
            },
        ),
        migrations.CreateModel(
            name="ProcessedTenKSectionThirteen",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ticker", models.CharField()),
                ("filing_date", models.DateField()),
                ("filing_url", models.TextField()),
                ("section_thirteen", models.TextField()),
            ],
            options={
                "db_table": "processed_ten_k_section_thirteen",
            },
        ),
        migrations.CreateModel(
            name="ProcessedTenKSectionThree",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ticker", models.CharField()),
                ("filing_date", models.DateField()),
                ("filing_url", models.TextField()),
                ("section_three", models.TextField()),
            ],
            options={
                "db_table": "processed_ten_k_section_three",
            },
        ),
        migrations.CreateModel(
            name="ProcessedTenKSectionTwelve",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ticker", models.CharField()),
                ("filing_date", models.DateField()),
                ("filing_url", models.TextField()),
                ("section_twelve", models.TextField()),
            ],
            options={
                "db_table": "processed_ten_k_section_twelve",
            },
        ),
        migrations.CreateModel(
            name="ProcessedTenKSectionTwo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ticker", models.CharField()),
                ("filing_date", models.DateField()),
                ("filing_url", models.TextField()),
                ("section_two", models.TextField()),
            ],
            options={
                "db_table": "processed_ten_k_section_two",
            },
        ),
    ]
